//#define PACKAGE_VERSION "14.4.2"
//
//#define EXTERNAL_GSM             0
//#define EXTERNAL_LPC10           0
//#define HAVE_ALSA                0
//#define HAVE_AMRNB               0
//#define HAVE_AMRWB               0
//#define HAVE_AO                  0
//#define HAVE_BYTESWAP_H          0
//#define HAVE_COREAUDIO           0
//#define HAVE_FENV_H              0
//#define HAVE_FLAC                0
//#define HAVE_FMEMOPEN            0
//#define HAVE_FSEEKO              0
#define HAVE_GETTIMEOFDAY        1
//#define HAVE_GLOB_H              0
//#define HAVE_GSM                      0
//#define HAVE_ID3TAG              0
//#define HAVE_INTTYPES_H          0
//#define HAVE_IO_H                0
//#define HAVE_LAME_LAME_H         0
//#define HAVE_LAME_SET_VBR_QUALITY 0
//#define HAVE_LPC10                    0
//#define HAVE_LRINT               0
//#define HAVE_LTDL_H              0
//#define HAVE_MACHINE_SOUNDCARD_H 0
//#define HAVE_MAD_H               0
//#define HAVE_MAGIC               0
//#define HAVE_MKSTEMP             0
//#define HAVE_MP3                 0
//#define HAVE_OGG_VORBIS          0
//#define HAVE_OSS                 0
//#define HAVE_PNG                 0
//#define HAVE_POPEN               0
//#define HAVE_PULSEAUDIO          0
//#define HAVE_SNDFILE             0
//#define HAVE_SNDFILE_1_0_18      0
//#define HAVE_SNDIO               0
//#define HAVE_SPEEXDSP            0
//#define HAVE_STDINT_H            0
//#define HAVE_STRCASECMP          0
//#define HAVE_STRING_H            0
//#define HAVE_STRINGS_H           0
//#define HAVE_STRRSTR             0
//#define HAVE_SUN_AUDIO           0
//#define HAVE_SUN_AUDIOIO_H       0
//#define HAVE_SYS_AUDIOIO_H       0
//#define HAVE_SYS_SOUNDCARD_H     0
//#define HAVE_SYS_STAT_H          0
//#define HAVE_SYS_TIMEB_H         0
//#define HAVE_SYS_TIME_H          0
//#define HAVE_SYS_TYPES_H         0
//#define HAVE_SYS_UTSNAME_H       0
//#define HAVE_TERMIOS_H           0
//#define HAVE_UNISTD_H            0
//#define HAVE_VSNPRINTF           0
//#define HAVE_WAVPACK             0
//#define WORDS_BIGENDIAN          0
