#define PACKAGE_VERSION "14.4.2"

#define EXTERNAL_GSM             1
#define EXTERNAL_LPC10           1
#define HAVE_ALSA                1
#define HAVE_AMRNB               1
#define HAVE_AMRWB               1
#define HAVE_AO                  1
#define HAVE_BYTESWAP_H          1
#define HAVE_COREAUDIO           1
#define HAVE_FENV_H              1
#define HAVE_FLAC                1
#define HAVE_FMEMOPEN            1
#define HAVE_FSEEKO              1
#define HAVE_GETTIMEOFDAY        1
#define HAVE_GLOB_H              1
#define HAVE_GSM                      1
#define HAVE_ID3TAG              1
#define HAVE_INTTYPES_H          1
#define HAVE_IO_H                1
#define HAVE_LAME_LAME_H         1
#define HAVE_LAME_SET_VBR_QUALITY 1
#define HAVE_LPC10                    1
#define HAVE_LRINT               1
#define HAVE_LTDL_H              1
#define HAVE_MACHINE_SOUNDCARD_H 1
#define HAVE_MAD_H               1
#define HAVE_MAGIC               1
#define HAVE_MKSTEMP             1
#define HAVE_MP3                 1
#define HAVE_OGG_VORBIS          1
#define HAVE_OSS                 1
#define HAVE_PNG                 1
#define HAVE_POPEN               1
#define HAVE_PULSEAUDIO          1
#define HAVE_SNDFILE             1
#define HAVE_SNDFILE_1_0_18      1
#define HAVE_SNDIO               1
#define HAVE_SPEEXDSP            1
#define HAVE_STDINT_H            1
#define HAVE_STRCASECMP          1
#define HAVE_STRING_H            1
#define HAVE_STRINGS_H           1
#define HAVE_STRRSTR             1
#define HAVE_SUN_AUDIO           1
#define HAVE_SUN_AUDIOIO_H       1
#define HAVE_SYS_AUDIOIO_H       1
#define HAVE_SYS_SOUNDCARD_H     1
#define HAVE_SYS_STAT_H          1
#define HAVE_SYS_TIMEB_H         1
#define HAVE_SYS_TIME_H          1
#define HAVE_SYS_TYPES_H         1
#define HAVE_SYS_UTSNAME_H       1
#define HAVE_TERMIOS_H           1
#define HAVE_UNISTD_H            1
#define HAVE_VSNPRINTF           1
#define HAVE_WAVPACK             1
#define WORDS_BIGENDIAN          1
